<?php include_once('script.php');
include_once('Config.php');?>


<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>C2C BUSSINESS</title>
    <link rel="stylesheet" href="style.css">

</head>

<body>

<!----------------------------------------------HEADER------------------------------------------------------------->

<?php include ("ZHeader.php")?>

<!----------------------------------------------ABOUT------------------------------------------------------------->

 


















 <!----------------------------------------------footer------------------------------------------------------------->

    <?php include ("ZFooter.php")?>

    




</body>

</html>